### ISSUE TITLE
Support multi-file logs

### ISSUE THREAD

**Issue by gillima** [leupibr/pycolog#5]
**Is your feature request related to a problem? Please describe.**
Modern loggers allow to span logs over multiple files especially for long time logs. Currently its not possible to navigate/filter across this mulit-file logs

**Describe the solution you'd like**
To analyze such logs it would be great if `pycolog` provides a feature to concatenate such logs based on a filename pattern.

**Comment by leupibr** [comment]
@gillima is this intended for a log rotate behavior or if a log gets split in e.g. DEBUG and ERROR logs?

**Comment by gillima** [comment]
@leupibr The idea is to have support for log rotate
